### ISSUE TITLE
Make file type exported ('File')

### ISSUE THREAD

**Issue by rickb777** [go-mail/gomail#28]
`type file struct { ... }` is unexported. This means that clients cannot define their own `file`s, nor even `FileSetting`s.

This makes it hard to add small attachments, e.g. vCards.

The workaround is to write every attachment to a temporary file. But this is painful because it's wasteful and it needs extra cleanup code.

Far better would be to export type `file` as `File`.

**Comment by rickb777** [comment]
Would you like a PR for this?

**Comment by pedromorgan** [comment]
@rickb777 makes sense..

**Comment by rickb777** [comment]
It's not strictly necessary, as I later discovered, but it would still be nice to have because it would be more obvious to new users.
