### ISSUE TITLE
SetBody as html template view file?

### ISSUE THREAD

**Issue by rebootcode** [go-mail/gomail#29]
Is there any possibility? that we can use "template view" file for 
`m.SetBody("text/html", "....view file.. path here"` 

Thanks

**Comment by cryptix** [comment]
Have you seen [SetBodyWriter](https://godoc.org/github.com/go-mail/mail#Message.SetBodyWriter)? Take a look at the example.

I don't think it makes sense to bundle templating into this library as it violates the separation of concerns.
