### ISSUE TITLE
messageWriter.writeString shouldn't ignore IO errors

### ISSUE THREAD

**Issue by ghost** [go-mail/gomail#30]
```
func (w *messageWriter) writeString(s string) {
	n, _ := io.WriteString(w.w, s)
	w.n += int64(n)
}
```

Error return by io.WriteString is silently ignored.

**Comment by cryptix** [comment]
Where do you found this?

I think you mean [this code from the forked gomail](https://github.com/go-gomail/gomail/blob/81ebce5c23dfd25c6c67194b37d3dd3f338c98b1/writeto.go#L160) ? This isn't part of this codebase, if at all it was turned into [newCopier() in message.go](https://github.com/go-mail/mail/blob/c55e3fbae0e229d9e12a420a81dd465880ae6b5b/message.go#L213) which looks fine.

**Comment by ghost** [comment]
[writeto.go](https://github.com/go-mail/mail/blob/c55e3fbae0e229d9e12a420a81dd465880ae6b5b/writeto.go#L163)

**Comment by cryptix** [comment]
Looks like I was holding that totally wrong.

Sorry, you are right and I agree that it should set `w.err` and not ignore it.

**Comment by cryptix** [comment]
@LethalRes check the PR I just made

**Comment by ivy** [comment]
@LethalRes This should be fixed now. Thanks again @cryptix! :+1:
