### ISSUE TITLE
Emails are getting send even if Send() panics

### ISSUE THREAD

**Issue by kdecher** [go-mail/gomail#32]
My Problem : 
Emails are getting send even if it panics

i`m getting this error :
gomail: could not send email 1: open ./pdf/fd.pdf: no such file or directory

There is no pdf(thats right) . He gives me the error , panics, but the emails are still going out.
There is an empty file attached with the name of the file it couldn't find.
They are send inside a Goroutine.

d := mail.NewDialer(smtpserver, port, login, passwort) 
seve, err := d.Dial()
if err != nil {
	log.Fatal("Konnte keine Verbindung zum Mailserver herstellen")
}

---Goroutine starts---
//stuff for validating the email recipient
//stuff for getting email body

m := mail.NewMessage()
m.SetHeader("From", absender)
m.SetHeader("To", emails)
m.SetHeader("Subject", fmt.Sprintf(Betreff, nummern))
m.SetBody("text/html", result)
m.Attach(pdfort + nummern + ".pdf")

if err := mail.Send(seve, m); err != nil {
 panic(err)  <-- panic occurs
}

m.reset()
---Goroutine end---

I got absolutely no clues and i couldn't find anything about it anywhere.
(I also tried it with DialAndSend before)

**Comment by cryptix** [comment]
Hmm..

I think this is the unfortunate side-effect of not buffering but sending directly to the tcp connection although, I think, it should still be possible to abort the crafting of a mail at that stage?

An alternative (but would be a breaking change of the API) might be returning an error from `m.Attach` which could stat/try to open the file earlier...
