### ISSUE TITLE
x509: certificate is valid for ..., not ...

### ISSUE THREAD

**Issue by nifflin** [go-mail/gomail#45]
SMTP client like thunderbird works well after TLS/SSL/STARTTLS being closed.

But can't access mailbox by github.com/go-mail/mail or github.com/go-gomail/gomail. Output same errors.

**Comment by chmike** [comment]
This error message is returned when the certificate name doesn’t match the name used for the connection.  

For instance, if you try to connect to host A, but the host A returns a certificate with name B, you will get the error message "x509: certificate is valid for B, not A". Change the server name from A to B in go-mail.

**Comment by nifflin** [comment]
thanks for your explanation

this error happens when I access ResellerClub.com mailbox system using go-mail/mail, it seem that can't close SSL/TLS/STARTTLS in go-mail/mail.

But in thunderbird, I can access mailbox if I switch off the SSL/TLS/STARTTLS option, no error is shown.

**Comment by chmike** [comment]
You have to set the field `StartTLSPolicyˋ of the dialer created with ˋNewDialer()ˋ to the value ˋmail.NoStartTLSˋ. The mail will be sent without using ˋStartTLSˋ.

**Comment by nifflin** [comment]
I tried like what you said, but I was told "unencrypted connection" error
just like https://github.com/go-mail/mail/issues/27

**Comment by chmike** [comment]
Your initial issue text is unclear. Are you trying to access your mailbox ? go-mail is only for sending mail.

What type of connection is required by your mail server to send mail ? Is a login-password required ? Is StartTLS required ? 

What port number do you use to send mail ? What address do you provide to send mail ? 

If sending mail works with thunderbird, what configuration parameters does it use ?

**Comment by chmike** [comment]
go-mail output the error "gomail: unencrypted connection" when a login is attempted with the TLS connection disabled. One can't use `NewDialer()` with a login name and password and disable TLS at the same time.

This is what I use

```Go
d := mail.Dialer{Host: "localhost", Port: 25, StartTLSPolicy: mail.NoStartTLS}
m := mail.NewMessage()
m.SetHeader("From", mailSrc)
m.SetHeader("To", mailDst...)
m.SetHeader("Subject", "Subject text")
m.SetBody("text/plain", "this is my mail message")
if err := d.DialAndSend(m); err != nil {
	panic(err)
}
```

Replace "localhost" with your target mail server name. But keep in mind that mail servers usually don't accept mail forwarding to avoid spamming. Does ResellerClub.com accept mail forwarding ?

**Comment by nifflin** [comment]
yes, resellerclub mail server has MX/CNAME forwarding, x509 error with TLS/STARTTLS/SSL, "unencrypted connection" error (username password required all the time) without TLS/STARTTLS/SSL.

**Comment by chmike** [comment]
If the user name and password are required by resellerclub, then you must use TLS and ˋNewDialer()ˋ. You then need to check the server name you provide to get the dialer. It must match the one in the certificate returned by the server. 

If you provide the server name and port number you use, I can try to see what server name is in the certificate.

**Comment by nifflin** [comment]
Test Email Account has sent to your email: christophe.meessen@gmail.com.

IMAP Server: imap.quant.lol
SMTP Server: smtp.quant.lol

ResellerClub customer service told me all ports are default. I found the complete addresses with port:

SMTP Address (NO SSL/TLS/STARTTLS): smtp.quant.lol:587
IMAP Address (NO SSL/TLS/STARTTLS): imap.quant.lol:143

**Comment by chmike** [comment]
Please remove your password ASAP. You really should now change it. This was not necessary.

Could you try to connect with a dialer obtained with NewDialer to the server "us2.smtp.mailhostbox.com" instead of "smtp.quant.lol" ? It could be that the certificate is for "us2.smtp.mailhostbox.com". 

The imap port is for unencrypted imap. This is unsafe. You should use port 993 that is for TLS encrypted imap. Go-mail doesn't use imap, so this is not relevant. Go-mail is only to send mail and it uses smtp. 

You really should use TLS with smtp too, otherwise your login name and password are sent in clear text through internet. This is unsafe, and should be avoided. And Go-mail won't allow this. It will return an error if you try to do this.

**Comment by chmike** [comment]
I tried and as I expected the full error message is the following:

`x509: certificate is valid for us2.smtp.mailhostbox.com, www.us2.smtp.mailhostbox.com, not smtp.quant.lol
`
Changing the server name to `us2.smtp.mailhostbox.com` fixed the error. This uses TLS. 
You probably need to do the same thing to connect to imap at port 993 with TLS. This will be secure. 

Here is the code I used that worked. 

```Go
package main

import (
	"fmt"

	"github.com/go-mail/mail"
)

func main() {
	fmt.Println("Try sending mail...")
	d := mail.NewDialer("us2.smtp.mailhostbox.com", 587, "test@quant.lol", "XYZ")
	m := mail.NewMessage()
	m.SetHeader("From", "test@quant.lol")
	m.SetHeader("To", "xxx@yyy.com")
	m.SetHeader("Subject", "Test !!!")
	m.SetBody("text/plain", "This is a test")
	if err := d.DialAndSend(m); err != nil {
		fmt.Println("Failed sending mail")
		panic(err)
	}
	fmt.Println("Mail sent without error")
}
```

Replace "xxx@yyy.com" with your target email address. This test mail will appear as being sent by "test@quant.lol". Replace also the password "XYZ" by the real password.

**Comment by nifflin** [comment]
haha, I see, thank you very much.
