### ISSUE TITLE
UTF-8 in header

### ISSUE THREAD

**Issue by DeadNumbers** [go-mail/gomail#54]
When I set sender name to header on russian lang 
```Go
msg.SetHeader("From", "Владимир Путин <putin@kremlin.ru>")
```

have error `gomail: could not send email 1: gomail: invalid address "=?UTF-8?q?=D0=92=D0=B5=D1=80=D0=B0_=D0=91=D0=BE=D0=B3=D0=B4=D0=B0=D0=BD?= =?UTF-8?q?=D0=BE=D0=B2_<email@example.com>?=": mail: expected single address, got "?="`

How I can do this fix?

**Comment by awoo-chsewei** [comment]
try encode your display name before set it into header
`mime.BEncoding.Encode("UTF-8", displayName)`

**Comment by aaabbbccc-123** [comment]
u either use set SetAddressHeader or FormatAddress + SetHeader . <putin@kremlin.ru> cant be part of the encoded string.
