### ISSUE TITLE
Link between throttled mass mail and send account password prompts?

### ISSUE THREAD

**Issue by steviesama** [go-mail/gomail#57]
My client is sending emails...throttled 6 per minute...I use gomail to facilitate this...not that it's directly related. I wonder if anyone knows if using `dialAndSend()` or anything regularly would cause Office 365 to prompt for his password in Outlook all the time. This is the only correlation I can think of is that he uses this Emailer almost daily now...sending over a 100 emails usually...sometimes more.

He changed the password and it seems to have stopped for now...but I'm curious if that might have had something to do with it...and if there's something that can be done to prevent it? Settings wise or anything.

These emails aren't spam or anything...he does his business via email...when they get new units in...he matches them to customers and the customized emails shoot out.

Before it was through a desktop app and the mailing was handed off to the installed Outlook instance...so this was never a problem.

Steve

**Comment by ivy** [comment]
@steviesama My first thought is that the volume of email you're sending is flagging your client's account. Have a look [here](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits#receiving-and-sending-limits), it looks like there's a limit of 30 emails/minute.

I'd recommend looking into a transactional email provider like [Amazon SES](https://aws.amazon.com/ses/), [Mandrill](https://mandrill.com/), or [SendGrid](https://sendgrid.com/). They're a bit more robust and include some additional features like stats on bounces and spam reports. If you're looking for a hacky solution, you might `time.Sleep` between sends or implement some kind of throttling in your application.

Hope that helps!

**Comment by steviesama** [comment]
@ivy Thanks for the input...the transactional provider info is particularly useful. I don't think I am doing too much on the sending though...I had read about the 30 per minute thing...and I already have it throttled at 6 sends per minute...I mark the beginning of a send...and if the throttle timespan hasn't passed...I sleep for the difference and reset it.

Thanks again.
