### ISSUE TITLE
Project maintenance state

### ISSUE THREAD

**Issue by fraiss-c** [go-mail/gomail#61]
I can see that @ivy is still active on GitHub, but still, nothing has been committed on this repository for almost one year.
As this fork has been described as "Actively maintained fork of gomail", I would like to know if this project is still going to be maintained.
If not, is there any maintained and viable fork?

Sincerely,
Charles

**Comment by ivy** [comment]
To my knowledge, the project is stable. It's true, I haven't a lot of time recently to give serious focus to developing new features or solving some outstanding bugs caused by various edge-cases. I will, however, gladly give attention to anyone putting forth an effort to step up to the task of making an improvement in the health of this codebase.

**Comment by Neustradamus** [comment]
Dear all, it is possible to change your code?
Change from here:
- https://github.com/go-gomail/gomail
- https://github.com/go-gomail/gomail/issues/188
- https://github.com/go-mail/mail
- https://github.com/Shopify/gomail
- https://github.com/Shopify/gomail/issues/59
- https://github.com/ory/mail

It has been unmaintained and maybe one or more vulnerabilities :/

There are:
- https://github.com/xhit/go-simple-mail from @xhit
- https://github.com/wneessen/go-mail from @wneessen

Linked to:
- https://github.com/go-gomail/gomail/issues/182
- https://github.com/go-gomail/gomail/issues/163
- https://github.com/go-gomail/gomail/issues/142
- https://github.com/go-gomail/gomail/issues/108
- https://github.com/go-gomail/gomail/issues/104
- https://github.com/go-gomail/gomail/issues/105
- https://github.com/go-gomail/gomail/issues/94
- https://github.com/go-mail/mail/issues/78
- https://github.com/go-mail/mail/issues/73
- https://github.com/go-mail/mail/issues/61
