### ISSUE TITLE
SSL detection

### ISSUE THREAD

**Issue by jbguerraz** [go-mail/gomail#70]
Thank you for the library :) 

https://github.com/go-mail/mail/blob/f59b9b83a4e522098e3d3eb94e6f81850ad6e973/smtp.go#L60

This way of "detecting" SSL breaks freedom :) 

A port number shouldn't be used as a law, instead, this should be configurable: even if assumption that 465 port is probably SSL, it should be just a sane default, not a strict law.

**Comment by pior** [comment]
The NewDialer constructor is merely a helper for common use-cases. 
You can do:
```go
d := NewDialer(...)
d.SSL = false
```

**Comment by jbguerraz** [comment]
Thank you!
